version: '3'

services:
  scraper:
    build: .
    command: python -m app.main
    env_file:
      - .env
    volumes:
      - ./:/code
    depends_on:
      - worker

  worker:
    build: .
    command: celery -A app.worker.celery worker -c 10 -B --loglevel=INFO -Q periodic,regular
    env_file:
      - .env
    volumes:
      - ./:/code
    depends_on:
      - redis

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7-alpine