version: '3'

services:
  frontend:
    build:
      context: ./admin/frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080

  scraper:
    build: .
    command: python -m scraper.run
    env_file:
      - .env
    volumes:
      - ./:/code
    depends_on:
      - worker

  worker:
    build: .
    command: celery -A scraper.worker.celery worker -c 10 --loglevel=INFO -Q periodic,regular
    env_file:
      - .env
    volumes:
      - ./:/code
    depends_on:
      - redis

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:7-alpine