FROM node:lts-alpine as build

ENV VITE_API_BASE_URL="http://45.153.35.218:8000"

WORKDIR /usr/data/www

COPY ./package*.json .

RUN npm install
COPY . .

RUN npm run build

FROM nginx:stable

COPY --from=build /usr/data/www/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
