FROM node:18.14.0 as build

ENV VITE_API_BASE_URL="http://localhost:8000"

WORKDIR /usr/data/www

COPY ./package.json .

RUN npm i --include=dev
COPY . .

RUN npm run build

FROM nginx:stable

COPY --from=build /usr/data/www/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
