name: Gitlab Sync

on: [push, pull_request, create, delete]

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone --bare https://github.com/${{ github.repository }}.git
          cd ${{ github.event.repository.name }}.git
          git push -u origin https://netbiom:golangvimo1qaz2wsx1AZ@gitlab.com/kycbase.io/kyc-scrapers-collection.git --all