name: Gitlab Sync

on: [push, pull_request, create, delete]

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://gitlab.com/${{ github.repository }}.git
          git remote add origin1 https://netbiom:glpat-hSFxYkvJQnJa2jLy9T3C@gitlab.com/kycbase.io/kyc-scrapers-collection.git
          git push origin1 --all